version: '2'

services:
  app:
    image: levlaz/circleci-demo-js-express:0.2
    ports:
      - "80:8000"
    environment:
      NODE_ENV: production
      MONGO_URL: mongodb://db:27017/mern-starter
  db:
    image: mongo:3.2.11
    ports:
      - "27017:27017"

